---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  vars:
    homebrew_taps:
      - sanemat/font
    homebrew_packages:
      - ansible
      - bash
      - ctags
      - curl
      - exa
      - figlet
      - fontforge
      - ghq
      - git
      - gnu-sed
      - go
      - graphviz
      - jq
      - lolcat
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - peco
      - readline
      - { name: ricty, install_options: [powerline, vim-powerline] }
      - tmux
      - vim
      - wget

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{homebrew_taps}}"

    - name: brew パッケージのインストール
      homebrew: >
        name={{ item.name | default(item) }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{homebrew_packages}}"

    - name: solarized color scheme の取得
      git:
        repo=git://github.com/altercation/solarized.git
        dest=~/.ghq/github.com/altercation/solarized.git
        force=yes
        accept_hostkey=yes

    - name: ricty の配置
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/*Powerline.ttf ~/Library/Fonts/ && fc-cache -vf
      args:
          creates: ~/Library/Fonts/Ricty-Bold-Powerline.ttf
